<?php
/**
* Soap client Pelicano
*
* Autogenerated with the Yii extension wsdl2php.
*/



class SNzb
{
public $Id; //integer;
public $description; //string;
public $url; //string;
public $file_name; //string;
public $subt_url; //string;
public $subt_file_name; //string;
}

/**
* The soap client proxy class
*/
class Pelicano 
 {
	public $soapClient;

	private static $classmap = array(
		'SNzb'=>'SNzb',

);

function __construct($url='http://192.168.100.102/workspace/PelicanoS/index.php?r=nzb/wsdl')
{
	$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function getNextNZBs($integer)
{
	$SNzbArray = $this->soapClient->getNextNZBs($integer);
	return $SNzbArray;
}
}


