<?php
/**
* Soap client wsPelicanoC
*
* Autogenerated with the Yii extension wsdl2php.
*/



/**
* The soap client proxy class
*/
class wsPelicanoC 
 {
	public $soapClient;

	private static $classmap = array(

	);
	
	function __construct($url='/index.php?r=wsPelicanoC/wsdl')
	{
		ini_set ('soap.wsdl_cache_enabled',0);
		$url = "http://localhost/workspace/PelicanoC".$url;
		$this->soapClient = @new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
	}
	
	
	function addNewRipMovie($idMyMovie, $path, $parental_control)
	{
		
		$result = $this->soapClient->addNewRipMovie($idMyMovie, $path, $parental_control);
		RippedMovie::sincronizeWithServer();
		return $result;
	}
	
}


