<?php
/**
* Soap client wsSettings
*
* Autogenerated with the Yii extension wsdl2php.
*/



class ClientSettingsRequest extends SOAP2Array
{
	public $Id_device; //string;
	public $ip_v4; //string;
	public $port_v4; //integer;
	public $ip_v6; //string;
	public $port_v6; //integer;
}

class ServerAnydvdUpdateResponse
{
	public $version; //string;
	public $file_name; //string;
	public $download_link; //string;
}

class ServerSettingsRipperResponse
{
	public $drive_letter; //string;
	public $temp_folder_ripping; //string;
	public $final_folder_ripping; //string;
	public $time_from_reboot; //time;
	public $time_to_reboot; //time;
	public $mymovies_username; //string;
	public $mymovies_password; //string;
	
}

/**
* The soap client proxy class
*/
class wsSettings 
 {
	public $soapClient;

	private static $classmap = array(
		'ClientSettingsRequest'=>'ClientSettingsRequest',
		'ServerAnydvdUpdateResponse'=>'ServerAnydvdUpdateResponse',
);

function __construct($url='http://localhost/workspace/PelicanoS/index.php?r=wssettings/wsdl')
{
$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function setClientSettings($ClientSettingsRequest)
{
	$boolean = $this->soapClient->setClientSettings($ClientSettingsRequest);
	return $boolean;
}
function setAnydvdVersionDownloaded($idDevice,$version)
{
	return $this->soapClient->setAnydvdVersionDownloaded($idDevice,$version);
	
}
public function setAnydvdVersionInstalled($idDevice,$version)
{
	return $this->soapClient->setAnydvdVersionInstalled($idDevice,$version);
	
}
function checkForUpdate($idDevice)
{
	$ServerAnydvdUpdateResponse = $this->soapClient->checkForUpdate($idDevice);
	return $ServerAnydvdUpdateResponse;
}

 function getRipperSettings($idDevice)
{
	$serverSettingsRipperResponse = $this->soapClient->getRipperSettings($idDevice);
	return $serverSettingsRipperResponse;
}
}


