#!/usr/bin/env python
import os,sys,re
nzbName = re.escape(sys.argv[2])
f = open('/home/pelicano/sabnzbdTestFile', 'w')
f.write('File Created\n')
f.write('\n')
f.write(len(sys.argv))
f.write(nzbName)
f.write('\n')
f.write(str(sys.argv))
f.write('\n')
f.close()
exit()
cmd="/var/www/pelicano/protected/yiic nzb updatestatemovies --file_name=%s" %nzbName
os.system(cmd)
print "NZB ok : %s " %nzbName
exit()
