<?php
/**
* Soap client Pelicano
*
* Autogenerated with the Yii extension wsdl2php.
*/


class LogResponse
{
	public $Id_log_customer; //integer;
}

class LogRequest extends SOAP2Array
{
	public $Id_customer; //integer;
	public $log_date; //date;
	public $username; //string;
	public $description; //string;
	public $Id_log_type; //integer;
	public $Id_log_customer; //integer;
}

class RippedResponse
{
	public $Id_device; //string;
	public $Id_my_movie_disc; //string;
}

class MyMovieSOAP
{
	function __construct()
	{
		$this->myMovieSerieHeader = new MyMovieSerieHeaderSOAP;
	}
	
	/**
	* Set model attributes
	* @param Nab $model
	*/
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}
	
	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
			$this->$name=$value;
		else
			return false;
		return true;
	}
	
	public $Id; //string;
	public $type; //string;
	public $bar_code; //string;
	public $country; //string;
	public $local_title; //string;
	public $original_title; //string;
	public $sort_title; //string;
	public $aspect_ratio; //string;
	public $video_standard; //string;
	public $production_year; //string;
	public $release_date; //string;
	public $running_time; //string;
	public $description; //string;
	public $extra_features; //string;
	public $parental_rating_desc; //string;
	public $imdb; //string;
	public $rating; //string;
	public $data_changed; //string;
	public $covers_changed; //string;
	public $genre; //string;
	public $studio; //string;
	public $poster_original; //string;
	public $big_poster_original; //string;
	public $backdrop_original; //string;
	public $adult; //integer;
	public $Id_parental_control; //integer;
	public $is_serie; //integer;
	public $myMovieSerieHeader; //MyMovieSerieHeaderSOAP;
	public $Subtitle; //MyMovieSubtitleSOAP[];
	public $AudioTrack; //MyMovieAudioTrackSOAP[];
	public $Person; //MyMoviePersonSOAP[];
	public $certification; //string;
}

class MyMovieSubtitleSOAP
{
	/**
	* Set model attributes
	* @param Nab $model
	*/
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}
	
	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
			$this->$name=$value;
		else
			return false;
		return true;
	}
	
	public $language; //string;
}

class MyMovieAudioTrackSOAP
{
	/**
	* Set model attributes
	* @param Nab $model
	*/
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}
	
	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
			$this->$name=$value;
		else
			return false;
		return true;
	}
	
	public $language; //string;
	public $type; //string;
	public $chanel; //string;
}

class MyMoviePersonSOAP
{
	/**
	 * Set model attributes
	 * @param Nab $model
	 */
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}

	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
			$this->$name=$value;
		else
			return false;
		return true;
	}

	public $name; //string;
	public $type; //string;
	public $role; //string;
	public $photo_original; //string;
}

class MyMovieSerieHeaderSOAP
{
	function __construct()
	{
		$this->myMovieSeason = new MyMovieSeasonSOAP;
	}
	
	/**
	* Set model attributes
	* @param Nab $model
	*/
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}
	
	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
			$this->$name=$value;
		else
			return false;
		return true;
	}
	
	public $Id; //string;
	public $description; //string;
	public $poster_original;
	public $big_poster_original;
	public $genre; //string;
	public $name; //string;
	public $sort_name; //string;
	public $rating; //string;
	public $original_network; //string;
	public $original_status; //string;
	public $myMovieSeason; //MyMovieSeasonSOAP;
}

class MyMovieSeasonSOAP
{
	/**
	* Set model attributes
	* @param Nab $model
	*/
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}
	
	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
			$this->$name=$value;
		else
			return false;
		return true;
	}
	
	public $season_number; //integer;
	public $banner_original; //string;
	public $Episode; //MyMovieEpisodeSOAP[];
}

class MyMovieEpisodeSOAP
{
	/**
	* Set model attributes
	* @param Nab $model
	*/
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}
	
	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
			$this->$name=$value;
		else
			return false;
		return true;
	}
	
	public $episode_number; //integer;
	public $description; //string;
	public $name; //string;
}

class MyMovieDiscSOAP
{
	/**
	* Set model attributes
	* @param Nab $model
	*/
	public function setAttributes($model)
	{
		//set attributes
		$attributesArray = $model->attributes;
		while (($value = current($attributesArray)) !== false) {
			$this->setAttribute(key($attributesArray), $value);
			next($attributesArray);
		}
	}
	
	public function setAttribute($name,$value)
	{
		if(property_exists($this,$name))
		$this->$name=$value;
		else
		return false;
		return true;
	}
	
	public $Id; //string;
	public $name; //string;
	public $Id_my_movie; //string;
	public $Id_my_movie_nzb; //string;
}

class RippedRequest extends SOAP2Array
{
	function __construct()
	{
		$this->myMovie = new MyMovieSOAP;
		$this->myMovieDisc = new MyMovieDiscSOAP;
	}
	
	public $myMovie; //MyMovieSOAP;
	public $myMovieDisc; //MyMovieDiscSOAP;
	public $ripped_date; //date;
	public $Id_device; //string;
}

class NzbResponse
{
	public $nzb; //NzbSOAP;
	public $myMovie; //MyMovieSOAP;
	public $myMovieDisc; //MyMovieDiscSOAP;
	public $MarketCategories;//integer[];	
}

class NzbStateRequest extends SOAP2Array
{
	public $Id_device; //string;
	public $Id_nzb; //integer;
	public $Id_state; //integer;
	public $change_state_date; //integer;
	public $points; //integer;
}

class TransactionResponse extends SOAP2Array
{
	public $Id; //integer;
	public $Id_customer; //integer;
	public $points; //integer;
	public $Id_transaction_type; //integer;
	public $description; //string;
}

/**
* The soap client proxy class
*/
class Pelicano 
 {
	public $soapClient;

	private static $classmap = array(
		'NzbResponse'=>'NzbResponse',
		'NzbStateRequest'=>'NzbStateRequest',
		'TransactionResponse'=>'TransactionResponse',
		'RippedResponse'=>'RippedResponse',
		'RippedRequest'=>'RippedRequest',
		'LogRequest'=>'LogRequest',
		'LogResponse'=>'LogResponse',

);

function __construct($url='/index.php?r=nzb/wsdl')
{
	ini_set ('soap.wsdl_cache_enabled',0);
	
	$url = Setting::getInstance()->host_name.Setting::getInstance()->host_path.'/index.php?r=nzb/wsdl';
	try {
		$this->soapClient = @new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));		
	} catch (SoapFault $fault) {
		$var  = $fault;	
	} catch (Exception $e) {
		$var  = $e;
	}
}
function getRipped($idDevice)
{
	$RippedResponseArray = array();
	if(isset($this->soapClient))
	{
		$RippedResponseArray = $this->soapClient->getRipped($idDevice);
	}
	return $RippedResponseArray;
}

function getNewNzbs($Id_device)
{
	$NzbResponseArray = array();
	if(isset($this->soapClient))
	{
		$NzbResponseArray = $this->soapClient->getNewNzbs($Id_device);
	}
	return $NzbResponseArray;		
}
function getTestNzbs($Id_device)
{
	$NzbResponseArray = array();
	if(isset($this->soapClient))
	{
		$NzbResponseArray = $this->soapClient->getTestNzbs($Id_device);
	}
	return $NzbResponseArray;
}

function updateCustomer($CustomerRequest)
{
	$result = false;
	if(isset($this->soapClient))
	{
		$result = $this->soapClient->updateCustomer($CustomerRequest);
	}
	return $result;
}
function setLog($LogRequestArray)
{
	$result = false;
	if(isset($this->soapClient))
	{
		$r = array();
		foreach ($LogRequestArray as $item)
		{
			$r[]=$item->toArray();
		}
		$result = $this->soapClient->setLog($r);
	}
	return $result;
}
function setRipped($RippedRequestArray)
{
	$result = false;
	if(isset($this->soapClient))
	{
		$r = array();
		foreach ($RippedRequestArray as $item)
		{
			$r[]=$item->toArray();
		}
		$result = $this->soapClient->setRipped($r);
	}
	return $result;
}
function setNzbState($NzbStateRequestArray)
{
	$result = false;
	if(isset($this->soapClient))
	{
		$r = array();
		foreach ($NzbStateRequestArray as $item)
		{
			$r[]=$item->toArray();
		}
		$result = $this->soapClient->setNzbState($r);
	}
	return $result;
}

function getPoints($Id_customer, $Id_transaction)
{
	$result = array();
	if(isset($this->soapClient))
	{
		
		$result = $this->soapClient->getPoints($Id_customer, $Id_transaction);
	}
	return $result;
}

function getConsumptions($Id_device)
{
	$ConsumptionResponseArray = array();
	if(isset($this->soapClient))
	{
		$ConsumptionResponseArray = $this->soapClient->getConsumptions($Id_device);
	}
	return $ConsumptionResponseArray;
}

function ackGetConsumptions($Id_device)
{
	$result = false;
	if(isset($this->soapClient))
	{
		$result = $this->soapClient->ackGetConsumptions($Id_device);
	}
	return $result;
}
}


