<?php
/**
* Soap client wsPelicanoC
*
* Autogenerated with the Yii extension wsdl2php.
*/



/**
* The soap client proxy class
*/
class wsPelicanoC 
 {
	public $soapClient;

	private static $classmap = array(

	);
	
	function __construct($url='/index.php?r=wsPelicanoC/wsdl')
	{
		ini_set ('soap.wsdl_cache_enabled',0);
		$url = Setting::getInstance()->host_name.Setting::getInstance()->host_path."/index.php?r=wsPelicanoC/wsdl";
		
		$url = "http://localhost/workspace/PelicanoC".$url;
		$this->soapClient = @new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
	}
	
	
	function addNewRipMovie($idMyMovie, $path, $parentalControl, $idDisc)
	{
		return $this->soapClient->addNewRipMovie($idMyMovie, $path, $parentalControl, $idDisc);
	}
	
}


