<?php
/**
* Soap client Pelicano
*
* Autogenerated with the Yii extension wsdl2php.
*/



class MovieResponse
{
public $Id; //integer;
public $url; //string;
public $file_name; //string;
public $subt_url; //string;
public $subt_file_name; //string;
public $ID; //string;
public $Title; //string;
public $Year; //string;
public $Rated; //string;
public $Released; //string;
public $Genre; //string;
public $Director; //string;
public $Writer; //string;
public $Actors; //string;
public $Plot; //string;
public $Poster; //string;
public $Runtime; //string;
public $Rating; //string;
public $Votes; //string;
public $Response; //string;
}

class MovieStateRequest
{
public $id_customer; //integer;
public $id_movie; //integer;
public $id_state; //integer;
}

/**
* The soap client proxy class
*/
class Pelicano 
 {
	public $soapClient;

	private static $classmap = array(
		'MovieResponse'=>'MovieResponse',
		'MovieStateRequest'=>'MovieStateRequest',

);

function __construct($url='http://192.168.100.106/workspace/PelicanoS/index.php?r=nzb/wsdl')
{
$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function getNewMovies($integer)
{
	$MovieResponseArray = $this->soapClient->getNewMovies($integer);
	return $MovieResponseArray;
}

function setMovieState($MovieStateRequest)
{
	//$boolean = $this->soapClient->setMovieState(array($MovieStateRequest->id_customer,$MovieStateRequest->id_movie,$MovieStateRequest->id_state));
	$boolean = $this->soapClient->__call("setMovieState", array($MovieStateRequest->id_customer,$MovieStateRequest->id_movie,$MovieStateRequest->id_state));
	return $boolean;
}
}


