<?php
/**
* Soap client wsPelicanoC
*
* Autogenerated with the Yii extension wsdl2php.
*/



/**
* The soap client proxy class
*/
class wsPelicanoC 
 {
	public $soapClient;

	private static $classmap = array(

	);
	
	function __construct($url='/index.php?r=wsPelicanoC/wsdl')
	{
		ini_set ('soap.wsdl_cache_enabled',0);
		$url = "http://192.168.100.100/workspace/PelicanoC".$url;
		$this->soapClient = @new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
	}
	
	
	function addNewRipMovie($string, $path, $parental_control)
	{
		return $this->soapClient->addNewRipMovie($string, $path, $parental_control);
	}
	
}


