<?php
/**
* Soap client wsSettings
*
* Autogenerated with the Yii extension wsdl2php.
*/



class ClientSettingsRequest extends SOAP2Array
{
	public $Id_device; //integer;
	public $ip_v4; //string;
	public $port_v4; //integer;
	public $ip_v6; //string;
	public $port_v6; //integer;
}

/**
* The soap client proxy class
*/
class wsSettings 
 {
	public $soapClient;

	private static $classmap = array(
		'ClientSettingsRequest'=>'ClientSettingsRequest',

);

function __construct($url='http://localhost/workspace/PelicanoS/index.php?r=wssettings/wsdl')
{
$this->soapClient = new SoapClient($url,array("classmap"=>self::$classmap,"trace" => true,"exceptions" => true));
}


function setClientSettings($ClientSettingsRequest)
{
	$boolean = $this->soapClient->setClientSettings($ClientSettingsRequest);
	return $boolean;
}
function setAnydvdVersionDownloaded($idDevice,$version)
{
	return $this->soapClient->setAnydvdVersionDownloaded($idDevice,$version);
	
}
static public function sendAnydvdVersionInstalled($idDevice,$anydvdVersion)
{
	return $this->soapClient->sendAnydvdVersionInstalled($idDevice,$version);
	
}

}


